df1 <- read.csv("date_gi.csv", TRUE, fileEncoding = 'utf-8')
df2 <- read.csv("training_gi_new2.csv", TRUE, fileEncoding = 'utf-8')
df5 <- read.csv("date5.csv")
head(df1)
head(df2)
head(df5)
df3 <- merge(df2, df1, by='date')
df6 <- merge(df3, df5, by='date')
df7 <- read.csv("ccc.csv", TRUE, fileEncoding = 'utf-8')
head(df3)
head(df6)
head(df7)
df8 <- merge(df6, df7, by='dst')
head(df8)
write.csv(df3, file="mer_gi2.csv")
write.csv(df8, file="mer_gi6.csv")
head(df1)

head(df1)
