x <- c(1, 0, 2, 1, 1, 1, 0, 2, 1, 0,
       1, 1, 1, 0, 1, 3, 1, 0, 1, 1)
mean(x)
sort(x)
median(x)
table(x)
names(which.max(table(x)))
hist(x)
hist(x, probability = T)
boxplot(x, horizontal = T)
table(x)
barplot(table(x))
pie(table(x))
var(x)
sd(x)
mean(x)
sd(x)/mean(x)
